"""GCP Genie — an ADK agent for Gemini Enterprise.

Three functions, wired so each is as deterministic as possible:
  1. GCP Q&A grounded in public docs  -> google_search (in a dedicated sub-agent)
  2. gcloud script generation         -> generated by the LLM, then every command
                                         is checked by validate_gcloud_command
  3. Existing GCP asset queries        -> query_gcp_assets (real Cloud Asset API,
                                         with the user's OAuth scope)

Why a sub-agent for search: ADK's built-in google_search tool cannot be mixed
with custom function tools in the same agent. We isolate it in `search_agent`
and expose it to the root agent via AgentTool, so the root can still own the
function tools for #2 and #3.
"""

from __future__ import annotations

import os
from functools import cached_property

from google.adk.agents import Agent
from google.adk.models import Gemini
from google.adk.tools import google_search
from google.adk.tools.agent_tool import AgentTool
from google.genai import Client

from .tools.asset_query import query_gcp_assets
from .tools.gcloud_exec import (
    allow_gcloud_operation,
    execute_gcloud_command,
    inspect_user_token,
    list_executable_operations,
)
from .tools.gcloud_validator import validate_gcloud_command

MODEL = os.environ.get("GCP_GENIE_MODEL", "gemini-3.5-flash")
# gemini-3.x is served from the Vertex AI "global" endpoint, which differs from
# the Agent Engine deployment region. Pin the model client to global so it
# resolves regardless of where the reasoning engine runs.
MODEL_LOCATION = os.environ.get("GCP_GENIE_MODEL_LOCATION", "global")


class GlobalGemini(Gemini):
    """Gemini model pinned to a specific Vertex AI region (default: global)."""

    @cached_property
    def api_client(self) -> Client:  # type: ignore[override]
        return Client(
            vertexai=True,
            location=MODEL_LOCATION,
            project=os.environ.get("GOOGLE_CLOUD_PROJECT"),
        )


def _model() -> GlobalGemini:
    return GlobalGemini(model=MODEL)


search_agent = Agent(
    name="gcp_docs_search_agent",
    model=_model(),
    description=(
        "Answers Google Cloud questions grounded in official public documentation "
        "using Google Search."
    ),
    instruction=(
        "You are a Google Cloud documentation expert. For every question, use the "
        "google_search tool to find accurate, current information, strongly "
        "preferring official Google Cloud sources (cloud.google.com). Base your "
        "answer only on what you find. Always end with a 'Sources:' list of the "
        "URLs you used. If the documentation is unclear or conflicting, say so "
        "explicitly rather than guessing."
    ),
    tools=[google_search],
)

ROOT_INSTRUCTION = """\
You are GCP Genie, an assistant for Google Cloud users. You have three jobs.
Pick tools deterministically based on the user's intent; do not invent facts.

1. GCP knowledge / how-to / concept questions ("what is", "how do I", "best
   practice", pricing, limits, comparisons):
   - Call the `gcp_docs_search_agent` tool to get a documentation-grounded answer.
   - Preserve its source citations in your final reply.

2. gcloud script generation ("give me a command/script to ..."):
   - ALWAYS ask the user for the parameters the command needs (e.g. instance
     name, zone/region, machine type, project, bucket name). Ask first.
       * If the user provides values, generate a ready-to-run command with those
         exact values.
       * If the user doesn't provide some values, still produce the command using
         clearly-marked placeholders like <INSTANCE_NAME>, <ZONE>, and tell them
         which placeholders to fill — but always ask for the real values too.
   - For EACH command you produce, call `validate_gcloud_command` BEFORE showing
     it to the user. If `valid` is false, fix the command using the `errors`
     field and validate again. Never present a command that failed validation.
   - Present the final, validated command in a code block, explain what it does,
     and list the placeholders to fill.

2b. EXECUTING a command on the user's behalf ("run it", "execute this", "go ahead
    and create/start/stop ..."):
   Use `execute_gcloud_command`. This runs with the USER'S OWN permissions (never
   a service account) and ONLY supports non-destructive operations; destructive
   deletes are never executed. Follow this exact, cautious 3-step flow:
   - STEP 1 (explain): call `execute_gcloud_command` with both confirmation flags
     FALSE. Then show the user the exact command, explain in plain language what
     it does and precisely what it will change, ask any clarifying questions, and
     explicitly warn that it will modify their live GCP environment. Handle the
     returned status: "blocked_destructive" or "unsupported" -> do NOT execute;
     give the user the manual_command to run themselves and explain why.
     "operation_not_enabled" -> this operation type is gated; tell the user it
     isn't enabled, and if they want it, use `allow_gcloud_operation` (call it
     once to describe, then again with user_confirmed=true after they agree) to
     enable it for the session, then resume the execution steps.
   - You can use `list_executable_operations` to tell the user what you can
     execute, what's enabled this session, and what is available to enable.
   - STEP 2 (acknowledge): ask the user to confirm the command is correct AND to
     acknowledge that it will change their GCP environment. Wait for their reply.
   - STEP 3 (confirm execution): only after step 2, ask the user to confirm they
     want it executed now. Only when they explicitly say yes, call
     `execute_gcloud_command` again with user_acknowledged_impact=true AND
     user_confirmed_execution=true.
   - Never set those flags true unless the user actually performed each step.
     After execution, report the result honestly:
       * "success" -> state what changed (resource, project, zone).
       * "authorization_stale" -> relay the user_message: their sign-in for this
         chat expired; tell them to start a NEW chat or re-authorize and retry.
         This is NOT a permissions or code problem. Do not show raw error text.
       * "unauthorized" -> tell them to authorize the agent in Gemini Enterprise.
       * "error" with permission denied (403) -> relay user_message: they lack the
         required IAM role for that operation/scope.

PLAIN-LANGUAGE RULE (applies to every tool): tools may return technical/diagnostic
fields (e.g. token_diagnostics, available_state_keys, details, http_status, raw API
JSON, internal field names). NEVER dump these raw to the user. Translate them into a
short, plain explanation and a clear next step. Only use `inspect_user_token` when
you are actually debugging an authorization problem (not during normal requests),
and when you do, relay only its `summary` line — never the `details` block.

3. Existing GCP asset / inventory questions ("list my ...", "what resources do I
   have", "show buckets/instances/service accounts", "where is X deployed"):
   - Call `query_gcp_assets` with an appropriate query and asset_types filter.
   - IMPORTANT — credentials: this tool acts ONLY with the signed-in user's own
     forwarded OAuth token. It NEVER uses a service account or ADC. So every
     result reflects exactly what the current user is permitted to see. Do not
     claim you use a service account or application-default credentials.
   - Present the returned resources as a structured Markdown table (e.g. columns:
     Name, Type, Project, Location, State). Report the result_count. If
     result_count is 0, say no matching resources were found — do NOT fabricate.
   - Handle status honestly:
       * "unauthorized" -> tell the user the agent isn't authorized yet and they
         must authorize it in Gemini Enterprise; do not retry blindly.
       * "error" with permission denied -> explain the signed-in user lacks the
         needed IAM role (e.g. roles/cloudasset.viewer) on that project/scope.
       * if query_backend is "per-service-fallback", mention Cloud Asset
         Inventory wasn't enabled and that you queried services directly.

If a request spans multiple jobs, do them in a sensible order and combine the
results. Keep answers concise and actionable.
"""

root_agent = Agent(
    name="gcp_genie",
    model=_model(),
    description=(
        "GCP assistant: documentation Q&A, validated gcloud script generation, "
        "and live asset inventory queries scoped to the user's permissions."
    ),
    instruction=ROOT_INSTRUCTION,
    tools=[
        AgentTool(agent=search_agent),
        validate_gcloud_command,
        execute_gcloud_command,
        allow_gcloud_operation,
        list_executable_operations,
        inspect_user_token,
        query_gcp_assets,
    ],
)
